# Generated by Django 5.2 on 2025-05-21 14:08

from django.db import migrations

def add_categories(apps, schema_editor):
       Category = apps.get_model('shop', 'Category')
       categories = [
           ('Clothing', 'clothing'),
           ('Electronics', 'electronics'),
           ('Footwear', 'footwear'),
           ('Home & Kitchen', 'home-kitchen'),
           ('Accessories', 'accessories'),
       ]
       for name, slug in categories:
           Category.objects.get_or_create(name=name, slug=slug)
class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_slug_alter_product_image'),
    ]

    operations = [
    ]
